<?php
/** www.uqunie.com-2020:/html/index.phtml
 *
 * @created   2017-07-28
 * @version   1.0
 * @package   www.uqunie.com-2020
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<div data-i18n="true" data-lang="en">
	<h1>Welcome to uqunie.com</h1>
	<a href="dotcheck.html">Dot抜けチェック</a>
</div>
<style>
#container {
	_border: 1px solid white;
	margin: auto;
	_max-width: 1000px;
}

#container > article {
	height: 600px;
}

header {
	_border: 1px solid white;
	margin: 0;
}

footer {
	_border: 1px solid white;
	border-radius: 0.25em;
	padding: 0.5em;
	_background-color: #3f3030;
}
</style>
