<?php
/** op-module-bootstrap:/php/module-unix.phtml
 *
 * @created   2018-11-13
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
$t = explode('.', PHP_VERSION);
$v = $t[0].$t[1];

/*
//	...
$redhat = file_exists('/etc/redhat-release') ?? false;
$remi   = $v > 53 ? true: false;
$repo   = $remi ? "--enablerepo=remi-php{$v}": ' ';
*/

//	...
if( $file   = file_get_contents('/etc/os-release') ){
	foreach( explode("\n", $file) as $line ){
		list($key, $val) = explode('=', $line);
		$info[$key] = $val;
	}
}

//	...
switch( $info['ID'] ?? null ){
	case 'redhat':
		$pkg = 'yum';
		$sys = 'service';
		break;

	case 'debian':
		$pkg = 'apt';
		$sys = 'systemctl';
		break;
}

//	...
switch( $_SERVER['SERVER_SOFTWARE'] ){
	case 'LiteSpeed':
		$ws  = 'lsws';
		$php = 'lsphp' . PHP_MAJOR_VERSION . PHP_MINOR_VERSION;
		break;
}

?>
<pre><code><?php ?>
sudo <?= $pkg ?> install <?= $php ?>-<?= _OP_APP_BOOTSTRAP_ . PHP_EOL ?>
sudo <?= $sys ?> restart <?= $ws ?>
</code></pre>
