#!/usr/bin/env bash

# Calc git root
GIT_ROOT=`git rev-parse --show-superproject-working-tree`
if [ -z "$GIT_ROOT" ]; then
	GIT_ROOT=`git rev-parse --show-toplevel`
fi

# hook-the-hooks
HOOK_NAME=`basename $0`
${GIT_ROOT}/asset/git/hooks/hook-the-hooks.sh ${HOOK_NAME}

# Check if status
if [ $? -ne 0 ]; then
   exit 1
fi

#  Search ci.sh
if [ -e "ci.sh" ]; then
	SOURCE="ci.sh"
	if [ $? -ne 0 ]; then
		exit 1
	fi
elif [ -e ".ci.sh" ]; then
	SOURCE=".ci.sh"
	if [ $? -ne 0 ]; then
		exit 1
	fi
else
  echo "ci.sh does not exist."
  echo `pwd`
  exit 1
fi

#  Include ci.sh
echo "execute --> $SOURCE"
source "$SOURCE"
if [ $? -ne 0 ]; then
	exit 1
fi

#  Result
if [ $? -ne 0 ]; then
  exit 1
fi
